/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ApiGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BuildBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BuildComplete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BuildTrigger": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ConnectionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DashboardWeb": {
      "type": "sst.aws.React"
      "url": string
    }
    "DeploymentsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DomainsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "LogBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ProjectsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SessionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Web": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "WebSocketHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}