// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects/new": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/deployments/:deployId": {
    params: {
      "id": string;
      "deployId": string;
    };
  };
  "/deployments": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects/new" | "/projects/:id" | "/projects/:id/deployments/:deployId" | "/deployments" | "/login";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/projects-new.tsx": {
    id: "routes/projects-new";
    page: "/projects/new";
  };
  "routes/project-detail.tsx": {
    id: "routes/project-detail";
    page: "/projects/:id";
  };
  "routes/deployment-detail.tsx": {
    id: "routes/deployment-detail";
    page: "/projects/:id/deployments/:deployId";
  };
  "routes/deployments.tsx": {
    id: "routes/deployments";
    page: "/deployments";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/projects-new": typeof import("./app/routes/projects-new.tsx");
  "routes/project-detail": typeof import("./app/routes/project-detail.tsx");
  "routes/deployment-detail": typeof import("./app/routes/deployment-detail.tsx");
  "routes/deployments": typeof import("./app/routes/deployments.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};